version: '3.3'

services:
  sota_bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}