services:
  sota_bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    depends_on:
      - redis
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - app-network

  redis:
    image: bitnami/redis:7.2-debian-12
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./cache:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge